name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ec2-3-85-231-158.compute-1.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd CRUD-products/
          git pull origin main
          git reset --hard
          sudo mvn clean package -DskipTests
        
          # Kill any existing Spring Boot app
          sudo pkill -f 'java.*productsCrud' || true
        
          # Wait a bit for port to free up
          sudo sleep 3
        
          # Start new app in background
          sudo nohup java -jar target/productsCrud-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
        
          # Give it time to start
          sudo sleep 5
        
          # Confirm app is running
          sudo pgrep -f 'java.*productsCrud' && echo "App started!" || echo "Failed to start"
